// import React from 'react';
// import { storiesOf } from '@storybook/react';
// import { defaultTheme } from '../../themes/default';
// import { ThemeProvider } from 'emotion-theming';
// import { Accordion } from './Accordion';
// import { Box } from '../Box/Box';
// import { Text } from '../Text/Text';
// import { AccordionItem } from './AccordionItem';
// import { AccordionHeader } from './AccordionHeader';
// import { Flex } from '../Flex/Flex';
// import { AccordionPanel } from './AccordionPanel';
//
// const stories = storiesOf('Accordion', module);
// const items = [
//     {
//         header: 'What is staking?',
//         panel:
//             // eslint-disable-next-line max-len
//             'Staking is a secure system by which holders can use their capital to generate stable, passive income, without any further requirements on their part.',
//     },
//     {
//         header: 'What is Neutrino Dollar?',
//         panel:
//             // eslint-disable-next-line max-len
//             'Neutrino Dollar (USDN) is a crypto token that is algorithmically pegged to the US dollar. It is implemented on the Neutrino stablecoin protocol offering holders the ability to stake their tokens and receive rewards generated by the economy.',
//     },
//     {
//         header: 'What is Neutrino Dollar?',
//         panel:
//             // eslint-disable-next-line max-len
//             'Neutrino Dollar (USDN) is a crypto token that is algorithmically pegged to the US dollar. It is implemented on the Neutrino stablecoin protocol offering holders the ability to stake their tokens and receive rewards generated by the economy.',
//     },
// ];
//
// stories.add('simple', () => (
//     <ThemeProvider theme={defaultTheme}>
//         <Flex
//             justifyContent="center"
//             pt={40}
//             backgroundColor="main.$800"
//             height="100vh"
//             color="standard.$0"
//         >
//             <Box width={600}>
//                 <Accordion>
//                     {items.map((item, i) => (
//                         <AccordionItem key={i}>
//                             <AccordionHeader>
//                                 <Text>{item.header}</Text>
//                             </AccordionHeader>
//                             <AccordionPanel>
//                                 <Text>{item.panel}</Text>
//                             </AccordionPanel>
//                         </AccordionItem>
//                     ))}
//                 </Accordion>
//             </Box>
//         </Flex>
//     </ThemeProvider>
// ));
//
// stories.add('allowMultiple', () => (
//     <ThemeProvider theme={defaultTheme}>
//         <Flex
//             justifyContent="center"
//             pt={40}
//             backgroundColor="main.$800"
//             height="100vh"
//             color="standard.$0"
//         >
//             <Box width={600}>
//                 <Accordion allowMultiple defaultIndex={[0, 1]}>
//                     {[...items, ...items].map((item, i) => (
//                         <AccordionItem key={i} isDisabled={i === 1}>
//                             <AccordionHeader>
//                                 <Text>
//                                     {i === 1 ? ' I am disabled.' : item.header}
//                                 </Text>
//                             </AccordionHeader>
//                             <AccordionPanel>
//                                 <Text>{item.panel}</Text>
//                             </AccordionPanel>
//                         </AccordionItem>
//                     ))}
//                 </Accordion>
//             </Box>
//         </Flex>
//     </ThemeProvider>
// ));
//
// stories.add('with defaultIndex and onChange function', () => (
//     <ThemeProvider theme={defaultTheme}>
//         <Flex
//             justifyContent="center"
//             pt={40}
//             backgroundColor="main.$800"
//             height="100vh"
//             color="standard.$0"
//         >
//             <Box width={600}>
//                 <Accordion defaultIndex={1} onChange={alert}>
//                     {items.map((item, i) => (
//                         <AccordionItem key={i}>
//                             <AccordionHeader>
//                                 <Text>{item.header}</Text>
//                             </AccordionHeader>
//                             <AccordionPanel>
//                                 <Text>{item.panel}</Text>
//                             </AccordionPanel>
//                         </AccordionItem>
//                     ))}
//                 </Accordion>
//             </Box>
//         </Flex>
//     </ThemeProvider>
// ));
//
// stories.add('with scroll', () => (
//     <ThemeProvider theme={defaultTheme}>
//         <Flex
//             justifyContent="center"
//             pt={40}
//             backgroundColor="main.$800"
//             height="100vh"
//             color="standard.$0"
//         >
//             <Box width={400}>
//                 <Accordion>
//                     <AccordionItem>
//                         <AccordionHeader>
//                             <Text>What are the benefits of staking USDN?</Text>
//                         </AccordionHeader>
//                         <AccordionPanel>
//                             <Text>
//                                 USDN is a unique and innovative algorithmic. Its
//                                 advantages are best illustrated by a comparison
//                                 with the conventional banking system: 1. You
//                                 transfer your money to the bank. From now on,
//                                 your money belongs to the bank. 2. The bank
//                                 promises you interest from around 0.1-1% per
//                                 annum, depending on the country. In some
//                                 countries, banks even offer negative interest
//                                 rates – that is, they charge you for holding
//                                 your own money! 3. As a rule, the bank makes
//                                 payments at the end of the deposit period. If
//                                 you try to withdraw your money earlier, there
//                                 may be fees and you will lose the accrued
//                                 interest. 4. In addition, the bank will actively
//                                 ask you about the nature origin of the funds,
//                                 and will likely require documentation from you,
//                                 including evidence of your income and even the
//                                 income of your loved ones. By contrast, Neutrino
//                                 Dollar staking works as follows: 1. You do not
//                                 send your funds to another party. They remain
//                                 solely under your control, and all operations
//                                 are carried out through an independent public
//                                 smart contract . Each transaction is transparent
//                                 and public (without disclosing your personal 2.
//                                 The rate of earnings is not regulated by a third
//                                 party, and is significantly higher than any bank
//                                 any bank provides. For example, USDN is expected
//                                 to provide a yield of 10-25% per annum. 3. in in
//                                 in USDN occur daily. 4. Users can make sure that
//                                 their payments have occurred, or cancel their
//                                 stake and withdraw their funds at any time. They
//                                 will never lose the earnings they have already
//                                 have already accrued. 5. The smart contract will
//                                 never require any additional documentation. Your
//                                 staking balance and payouts are completely
//                                 anonymous.
//                             </Text>
//                         </AccordionPanel>
//                     </AccordionItem>
//
//                     <AccordionItem>
//                         <AccordionHeader>
//                             <Text>{items[0].header}</Text>
//                         </AccordionHeader>
//                         <AccordionPanel>
//                             <Text>{items[0].panel}</Text>
//                         </AccordionPanel>
//                     </AccordionItem>
//                 </Accordion>
//             </Box>
//         </Flex>
//     </ThemeProvider>
// ));
//
// stories.add('disabled', () => (
//     <ThemeProvider theme={defaultTheme}>
//         <Flex
//             justifyContent="center"
//             pt={40}
//             backgroundColor="main.$800"
//             height="100vh"
//             color="standard.$0"
//         >
//             <Box width={600}>
//                 <Accordion>
//                     {items.map((item, i) => (
//                         <AccordionItem key={i} isDisabled={i === 1}>
//                             <AccordionHeader
//                                 sx={{
//                                     '&[aria-disabled="true"]': {
//                                         backgroundColor: 'main.$1000',
//                                         color: 'basic.$700',
//                                     },
//                                 }}
//                             >
//                                 <Text>
//                                     {i === 1 ? ' I am disabled.' : item.header}
//                                 </Text>
//                             </AccordionHeader>
//                             <AccordionPanel>
//                                 <Text>{item.panel}</Text>
//                             </AccordionPanel>
//                         </AccordionItem>
//                     ))}
//                 </Accordion>
//             </Box>
//         </Flex>
//     </ThemeProvider>
// ));
//
// stories.add('custom styles', () => (
//     <ThemeProvider theme={defaultTheme}>
//         <Flex
//             justifyContent="center"
//             pt={40}
//             backgroundColor="main.$800"
//             height="100vh"
//             color="standard.$0"
//         >
//             <Box width={600}>
//                 <Accordion>
//                     {items.map((item, i) => (
//                         <AccordionItem key={i} isDisabled={i === 1}>
//                             <AccordionHeader
//                                 sx={{
//                                     '&[aria-disabled="true"]': {
//                                         backgroundColor: 'main.$1000',
//                                         color: 'basic.$700',
//                                     },
//                                     '&[aria-expanded="true"]': {
//                                         backgroundColor: 'success.$500',
//                                     },
//                                 }}
//                             >
//                                 <Text>
//                                     {i === 1 ? ' I am disabled.' : item.header}
//                                 </Text>
//                             </AccordionHeader>
//                             <AccordionPanel backgroundColor="primary.$700">
//                                 <Text>{item.panel}</Text>
//                             </AccordionPanel>
//                         </AccordionItem>
//                     ))}
//                 </Accordion>
//             </Box>
//         </Flex>
//     </ThemeProvider>
// ));
